name: "Setup env"
description: "Set-up Python and install dependencies"

inputs:
  python-version:
    description: "Python version"
    required: false
    type: string
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install .[dev-extra,test]
