name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    name: "Format with black"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: black --check .

  ruff:
    name: "Lint with ruff"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ruff check .

  pytest:
    name: "Run tests"
    runs-on: ubuntu-latest
    needs: [black, ruff]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          coverage run --branch -m pytest --pyargs piran
          coverage report -m
