name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    name: "black"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: black --check .

  isort:
    name: "isort"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: isort --check .

  ruff:
    name: "ruff"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: ruff check .

  pytest:
    name: "tests"
    runs-on: ubuntu-latest
    needs: [black, isort, ruff]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          coverage run --branch -m pytest --pyargs piran
          coverage report -m

  # adapted from https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup
    - name: Build HTML
      uses: ammaraskar/sphinx-action@8.0.2
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html